### ISSUE TITLE
RLS crash on invalid rls.toml file. Putting lsp-rust in an invalid state.

### ISSUE THREAD

**Issue by s-d-m** [emacs-lsp/lsp-rust#4]
When having an invalid `rls.toml` file at the root of the project (same level as `Cargo.toml`), rls will crash.
Running it with `RUST_BACKTRACE=1` produces the following stack trace in the `*Rust Language Server stderr ` buffer. Emacs also reports `lsp--stdio-send-sync: Timed out while waiting for a response from the language server` in the `*Message*` buffer (and the echo area).

```
thread '<unnamed>' panicked at 'Could not parse TOML: Error { inner: ErrorInner { kind: Wanted { expected: "an equals", found: "a colon" }, line: Some(0), col: 9, message: "", key: [] } }', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: rls::config::Config::from_path
  11: rls::server::LsService::handle_message::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  14: <F as alloc::boxed::FnBox<A>>::call_box
  15: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:658
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  16: start_thread
  17: __clone
```

running `lsp-capabilities` afterwards leads to a segfault in emacs.

How to reproduce the issue:

- Take a simple rust project (Hello world is enough)
- create a rls.toml file with invalid content (mine contained only the following line)
```
build_lib:false
```
- run `lsp-mode` in a rust buffer
- wait for the timeout
- run `lsp-capabilities`

**Comment by vibhavp** [comment]
Does Emacs actually segfault? That looks like a bug in Emacs too, which version are you using?

**Comment by alanz** [comment]
The stack trace is all rust code, maybe it is the stderr log, coming from the backend server?

**Comment by s-d-m** [comment]
@vibhavp yes emacs did segfault afterwards (I have the following stacktrace on my terminal):

```shell
Backtrace:
emacs[0x4a7465]
emacs[0x4b2bd4]
emacs[0x49c7fe]
emacs[0x474d31]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110c0)[0x7fa72d25a0c0]
emacs[0x43a248]
emacs[0x45cb85]
emacs[0x580395]
emacs[0x45c9ab]
emacs[0x46476a]
emacs[0x45ca99]
emacs[0x45e51c]
emacs[0x464bb8]
emacs[0x45cb76]
emacs[0x580395]
emacs[0x45c9ab]
emacs[0x580395]
emacs[0x45c9ab]
emacs[0x46476a]
emacs[0x45ca99]
emacs[0x45e380]
emacs[0x464bb8]
emacs[0x45cb76]
emacs[0x580395]
emacs[0x45c9ab]
emacs[0x45ccba]
emacs[0x4b174b]
emacs[0x45b9e2]
emacs[0x4aa6a4]
emacs[0x45ba8b]
emacs[0x4b2880]
emacs[0x4b2907]
emacs[0x4b2a28]
emacs[0x414731]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fa72c7a92b1]
emacs[0x416a1a]

[1]  + segmentation fault  emacs
```

I'm using an emacs I compiled myself. It was compiled at commit 8ca70e402ecab5d7e71e418af6866c8b02d4f757 (6months ago)
using the following command `./configure --disable-silent-rules --enable-link-time-optimization --disable-acl --without-pop --with-sound=no --with-x-toolkit=yes --with-xft --with-libotf --without-dbus --without-gconf --without-gsettings --without-selinux --with-file-notification=inotify --without-makeinfo --without-xpm --without-jpeg --without-gif`

i can send the `config.log` file if it helps.

I tried to update my emacs and recompile it to see if the bug was still present (before doing a bug report to the emacs team), but sadly it doesn't compile out-of-the-box anymore for me. I didn't investigate any further though.

I believe `lsp-mode` should be able to detect when a server dies. Creating a link to `/bin/false` named `rls` taking predecedence in the `PATH` over the real `rls` should do the trick to reproduce the issue.

This crash is 100% reproducible on my machine, so if you can't reproduce it with a newer emacs (compiled with the same options), maybe the segfault is already fixed.
